server.port=0

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/inventory-service
spring.datasource.username=postgres
spring.datasource.password=12345678

# PostgreSQL Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

eureka.client.serviceUrl.defaultZone=http://eureka:password@localhost:8761/eureka

spring.application.name=inventory-service